title: DataTables Paging Responsive
description: Plugin paging responsive for dataTables
bootstrap4_url: ./bootstrap4
bootstrap5_url: ./bootstrap5
defaults:
  -
    scope:
      path: "default.html"
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "bootstrap4.html"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "bootstrap4" # overrides previous default layout
  -
    scope:
      path: "bootstrap5.html"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "bootstrap5" # overrides previous default layout
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
